apiVersion: apps/v1
kind: Deployment
metadata:
  name: region-query-container
  labels:
    app: region-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: region-query
  template:
    metadata:
      labels:
        app: region-query
    spec:
      containers:
      - name: region-query
        image: "natanroberto182/region-query:latest"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: user-persistence-config
              key: ASPNETCORE_ENVIRONMENT
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
